#!/bin/bash

# Function to rename files
rename_files() {
    local pattern="$1"
    local replacement="$2"
    for file in *"$pattern"*.ovpn; do
        if [ -f "$file" ]; then
            new_name="${file//$pattern/$replacement}"
            mv "$file" "$new_name"
        fi
    done
}

# Rename all files
rename_files "Японія" "Japan"
rename_files "Швеція" "Sweden"
rename_files "Швейцарія" "Switzerland"
rename_files "Чилі" "Chile"
rename_files "Чехія" "Czech Republic"
rename_files "Франція" "France"
rename_files "Фінляндія" "Finland"
rename_files "Філіппіни" "Philippines"
rename_files "Україна" "Ukraine"
rename_files "Узбекистан" "Uzbekistan"
rename_files "Угорщина" "Hungary"
rename_files "Туреччина" "Turkey"
rename_files "Тайвань" "Taiwan"
rename_files "Таїланд" "Thailand"
rename_files "США" "USA"
rename_files "Словенія" "Slovenia"
rename_files "Словаччина" "Slovakia"
rename_files "Сінгапур" "Singapore"
rename_files "Сербія" "Serbia"
rename_files "Саудівська Аравія" "Saudi Arabia"
rename_files "Румунія" "Romania"
rename_files "Росія" "Russia"
rename_files "Пуерто-Рико" "Puerto Rico"
rename_files "Португалія" "Portugal"
rename_files "Польща" "Poland"
rename_files "Південна Корея" "South Korea"
rename_files "Перу" "Peru"
rename_files "ПАР" "South Africa"
rename_files "Пакистан" "Pakistan"
rename_files "Оман" "Oman"
rename_files "ОАЕ" "UAE"
rename_files "Норвегія" "Norway"

# Rename cities
rename_files "Токіо" "Tokyo"
rename_files "Стокгольм" "Stockholm"
rename_files "Цюрих" "Zurich"
rename_files "Сантьяго" "Santiago"
rename_files "Прага" "Prague"
rename_files "Париж" "Paris"
rename_files "Гельсінкі" "Helsinki"
rename_files "Маніла" "Manila"
rename_files "Миколаїв" "Mykolaiv"
rename_files "Київ" "Kyiv"
rename_files "Ташкент" "Tashkent"
rename_files "Будапешт" "Budapest"
rename_files "Стамбул" "Istanbul"
rename_files "Тайбей" "Taipei"
rename_files "Бангкок" "Bangkok"
rename_files "Чикаго" "Chicago"
rename_files "Сан-Франциско" "San Francisco"
rename_files "Нью-Йорк" "New York"
rename_files "Маямі" "Miami"
rename_files "Лос-Анджелес" "Los Angeles"
rename_files "Даллас" "Dallas"
rename_files "Вашингтон" "Washington"
rename_files "Буффало" "Buffalo"
rename_files "Любляна" "Ljubljana"
rename_files "Братислава" "Bratislava"
rename_files "Сінгапур" "Singapore"
rename_files "Белград" "Belgrade"
rename_files "Ер-Ріяд" "Riyadh"
rename_files "Бухарест" "Bucharest"
rename_files "Москва" "Moscow"
rename_files "Сан-Хуан" "San Juan"
rename_files "Лісабон" "Lisbon"
rename_files "Варшава" "Warsaw"
rename_files "Сеул" "Seoul"
rename_files "Ліма" "Lima"
rename_files "Йоганнесбург" "Johannesburg"
rename_files "Ісламабад" "Islamabad"
rename_files "Маскат" "Muscat"
rename_files "Фуджейра" "Fujairah"
rename_files "Дубай" "Dubai"
rename_files "Осло" "Oslo" 